### PR TITLE
feat: setup admin project

### PR DESCRIPTION
**Pull request by lukekeum**
Setup admin project \w Create React App (Typescript template)

### CODE REVIEW

**Comment by lukekeum** [comment]
good

**Review by II-DW — COMMENTED** [review]
good

**Review by 2ssunny — COMMENTED** [review]
good

**Review by II-DW — CHANGES_REQUESTED** [review]
goooood

**Review by II-DW — APPROVED** [review]
goood

**Comment by lukekeum** [comment]
Wrong direction

**Pull request closed without merging**
